:sparkles: feat : Implementação Tela de Cadastro
matheuszpher/FRONT-MYM pull request #8
Opened 2023-11-13 16:32 UTC by IagoFsv

Implementação Tela de Cadastro e input do Token

2023-11-13 17:18 UTC, SammyFerreiraa commented on my-monitor/src/app/(auth-routes)/cadastro/page.tsx
> +import { AsideHomePageCadastro } from '@/components/homepage'
import desnecessario

2023-11-13 17:18 UTC, SammyFerreiraa commented on my-monitor/src/app/(auth-routes)/cadastro/page.tsx
> +import { HeaderHomepage } from '@/components/homepage'
import desnecessário.

2023-11-13 17:20 UTC, SammyFerreiraa commented on my-monitor/src/components/cadastro/form-cadastro/FormCadastro.tsx
O FormCadastro.tsx deve ter apenas o Form dentro dele, e não uma <div>, refatore o código para deixar apenas o <form> dentro do FormCadastro.tsx.

2023-11-13 17:23 UTC, SammyFerreiraa commented on my-monitor/src/components/cadastro/form-cadastro/FormCadastro.tsx
> +        <Button
colocar a div com o botão de submit dentro do formulário.

2023-11-13 17:25 UTC, SammyFerreiraa commented on my-monitor/src/components/cadastro/form-cadastro/FormCadastro.tsx
> +        <p className="ml-6 relative mb-5 -top-2 text-center text-zinc-500 text-sm">
deixar essa mensagem na div que está fora do formulário mesmo.

2023-11-13 17:25 UTC, SammyFerreiraa commented on my-monitor/src/components/homepage/header/HeaderHomepage.tsx
> +}
por na pasta types e comentar falando o que é lá.

2023-11-13 17:26 UTC, SammyFerreiraa commented on my-monitor/src/components/cadastro/form-cadastro/FormCadastro.tsx
> +        </p>
deixar essa mensagem na div que está fora do formulário mesmo.

2023-11-13 17:26 UTC, SammyFerreiraa commented on my-monitor/src/components/cadastro/form-cadastro/FormCadastro.tsx
> +        </div>
colocar a div com o botão de submit dentro do formulário.

2023-11-13 17:30 UTC, SammyFerreiraa commented on my-monitor/src/components/cadastro/form-cadastro/FormCadastro.tsx
> +  });
a rota redirecionará para a "/login"

2023-11-13 17:45 UTC, SammyFerreiraa requested changes

2023-11-13 17:45 UTC, SammyFerreiraa commented on my-monitor/src/components/cadastro/form-cadastro/FormCadastro.tsx
> +          console.log("showAdditionalInput:", showAdditionalInput);
caso funcione, remova os console.log().

2023-11-13 17:45 UTC, SammyFerreiraa commented on my-monitor/src/components/cadastro/form-cadastro/FormCadastro.tsx
O FormCadastro.tsx deve ter apenas o form dentro dele, e não uma div, refatore o código para deixar apenas o form dentro do FormCadastro.tsx.

2023-11-13 17:45 UTC, SammyFerreiraa commented on my-monitor/src/components/cadastro/form-cadastro/FormCadastro.tsx
> +  });
a rota redirecionará para a "/login"

2023-11-13 17:45 UTC, SammyFerreiraa commented on my-monitor/src/components/cadastro/form-cadastro/FormCadastro.tsx
> +        </div>
colocar a div com o botão de submit dentro do formulário.

2023-11-13 17:45 UTC, SammyFerreiraa commented on my-monitor/src/components/cadastro/form-cadastro/FormCadastro.tsx
> +        </p>
deixar essa mensagem na div que está fora do formulário mesmo.

2023-11-13 17:45 UTC, SammyFerreiraa commented on my-monitor/src/components/homepage/header/HeaderHomepage.tsx
> +}
por na pasta types e comentar falando o que é lá.

2023-11-13 17:45 UTC, SammyFerreiraa commented on my-monitor/src/app/(auth-routes)/cadastro/page.tsx
> +import { AsideHomePageCadastro } from '@/components/homepage'
imports desnecessários.

2023-11-13 22:47 UTC, IagoFsv commented on my-monitor/src/components/homepage/header/HeaderHomepage.tsx
> +}
/**
 * Define as propriedades aceitas pelo componente HeaderHomepage.
 * @property logoSrc - O caminho da imagem do logotipo.
 * @property textColor - A cor do texto do cabeçalho.
 */
 
 posso por a descrição nesse estilo?
 
 Ou deixo no padrão?
 
 ex:

//Define as propriedades aceitas pelo componente HeaderHomepage.
export interface HeaderHomepageProps {
  logoSrc?: string;
  textColor?: string;
}

2023-11-13 23:55 UTC, SammyFerreiraa commented on my-monitor/src/components/homepage/header/HeaderHomepage.tsx
> +}
padrão mesmo.

2023-11-14 11:20 UTC, SammyFerreiraa approved these changes

2023-11-14 11:20 UTC, merged